name: Build CarTube IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Create build directory
        run: |
          mkdir -p build
          cd build
          if [ -e "CarTube.ipa" ]; then
            rm CarTube.ipa
          fi

      - name: Build app
        run: |
          xcodebuild -project "./CarTube.xcodeproj" \
            -scheme CarTube \
            -configuration Debug \
            -derivedDataPath "./build/DerivedData" \
            -destination 'generic/platform=iOS' \
            ONLY_ACTIVE_ARCH="NO" \
            CODE_SIGNING_ALLOWED="NO" \
            -verbose -showBuildTimingSummary | tee build/xcodebuild.log
        env:
          MD_APPLE_SDK_ROOT: /Applications/Xcode_16.2.app

      - name: Copy app to build directory
        run: |
          cp -r "./build/DerivedData/Build/Products/Debug-iphoneos/CarTube.app" "./build/CarTube.app"

      - name: Remove code signature
        run: |
          codesign --remove "./build/CarTube.app" || true
          rm -rf "./build/CarTube.app/_CodeSignature" || true
          rm -rf "./build/CarTube.app/embedded.mobileprovision" || true

      # ⛔️ Удалён шаг ldid (подпись не требуется для debug IPA)

      - name: Package IPA
        run: |
          cd build
          rm -rf Payload
          mkdir Payload
          cp -r CarTube.app Payload/CarTube.app
          zip -vr CarTube.ipa Payload
          rm -rf CarTube.app Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: CarTube-IPA
          path: build/CarTube.ipa
          retention-days: 7

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-log
          path: build/xcodebuild.log
          retention-days: 3
